[package]
name = "fontwriter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
fonttools = { git = "https://github.com/simoncozens/rust-font-tools.git" }
