name: React app deployment
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: wasm32-unknown-unknown
    - run: npm ci
    - run: npm run build
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git --work-tree build add --all
    - run: git commit -m "Automatic Deploy action run by github-actions"
    - run: git push origin HEAD:gh-pages --force